### ISSUE TITLE
Add ability to skip assertions in _test.go files.

### ISSUE THREAD

**Issue by rzajac** [gostaticanalysis/fourcetypeassert#16]

**Comment by rzajac** [comment]
It is already possible by adding below lines to `.golangci.yml` file.
  
```yaml
issues:
  exclude-rules:
    - path: (.+)_test.go
      linters:
        - forcetypeassert
```
